describe 'directive: ng-youtube-iframe', ->
  beforeEach angular.mock.module('ngYoutube')

  $compile = undefined
  $rootScope = undefined
  tpl = undefined
  $scope = undefined
  templateAsHtml = undefined
  browser_detector = undefined

  beforeEach angular.mock.inject((_$compile_, _$rootScope_) ->
    $compile = _$compile_
    $rootScope = _$rootScope_
    $scope = _$rootScope_.$new()
    tpl = $compile('<div id=\'ngYoutube\' ng-youtube height=300 width=700></div>')($scope)
    $scope.$digest()
    templateAsHtml = tpl[0].outerHTML
    return
  )
  it 'should have ng-youtube directive', ->
    expect(templateAsHtml).toContain 'ng-youtube'
    return
  it 'should have height defined', ->
    expect(templateAsHtml).toContain 'height'
    return
  it 'should have height equal to 300', ->
    expect(tpl.attr('height')).toEqual '300'
    return
  it 'should have width defined', ->
    expect(templateAsHtml).toContain 'width'
    return
  it 'should have width equal to 700', ->
    expect(tpl.attr('width')).toEqual '700'
    return
  return

# ---
# generated by js2coffee 2.2.0
